#ifndef BLACKSTRING_LEVEL_ZERO_LEGACY_COORDINATES_WRAPPER_HPP_
#define BLACKSTRING_LEVEL_ZERO_LEGACY_COORDINATES_WRAPPER_HPP_

#include "../Coordinates.hpp"

#endif /* BLACKSTRING_LEVEL_ZERO_LEGACY_COORDINATES_WRAPPER_HPP_ */
