#ifndef BLACKSTRING_LEVEL_ZERO_LEGACY_LAGRANGE_WRAPPER_HPP_
#define BLACKSTRING_LEVEL_ZERO_LEGACY_LAGRANGE_WRAPPER_HPP_

#include "../Lagrange.hpp"

#endif /* BLACKSTRING_LEVEL_ZERO_LEGACY_LAGRANGE_WRAPPER_HPP_ */
