#ifndef BLACKSTRING_GRAMR_DEFINE_COORDINATES_WRAPPER_HPP_
#define BLACKSTRING_GRAMR_DEFINE_COORDINATES_WRAPPER_HPP_

#include "../../Coordinates.hpp"

#endif /* BLACKSTRING_GRAMR_DEFINE_COORDINATES_WRAPPER_HPP_ */
