#ifndef BLACKSTRING_GRAMR_DEFINE_LAGRANGE_WRAPPER_HPP_
#define BLACKSTRING_GRAMR_DEFINE_LAGRANGE_WRAPPER_HPP_

#include "../../Lagrange.hpp"

#endif /* BLACKSTRING_GRAMR_DEFINE_LAGRANGE_WRAPPER_HPP_ */
