# Minimal dependency/header probe. This is not a production application.

CHOMBO_HOME ?= $(abspath ../../../../external/Chombo/lib)
GRCHOMBO_SOURCE ?= $(abspath ../../../../external/GRChombo/Source)
BLACKSTRING_SOURCE ?= $(abspath ../..)

ebase := BlackStringChomboHeaderProbe
LibNames := BoxTools

src_dirs :=

include $(CHOMBO_HOME)/mk/Make.test
